conversation/ShareJS

- src/server/db/pg.coffee
* continue to read from the TEXT column for now
* once the JSON column is fully populated there'll be a second commit
that reads from the JSON col
* node-postgres can automatically handle converting JS objects into JSON
when inserting, but unfortunately it doesn't convert JS arrays into
JSON arrays. To work around that we have to manually call
JSON.stringify when inserting ops and snapshots, and use ::json to
convert it inside postgres
> write snapshop and op data to JSON+TEXT cols

- src/server/db/pg.coffee
- src/server/model.coffee
- src/server/rest.coffee
- src/server/useragent.coffee
The existing REST API allows the latest version of a document to be requested using:
`GET /doc/123abc`
This expands the API to allow all snapshots to be retrieved as JSON:
`GET /doc/123abc/snapshots`
It works, but probably needs a bit of polish.
The tc app currently directly accesses the sharejs db tables to fetch this data and display it on the history scrubber. Once this endpoint is available, we can change tc to fetch the snapshots via the API. That removes the DB-level coupling, and we'll be free to move all sharejs data into a dedicated DB.
To test this, modify `packages.json` in the `tc-share`  repo to refer to this branch (`git://github.com/conversation/ShareJS.git#get-snapshots`) and then run `npm install`. Then start sharejs (`coffee app.coffee`) and use curl to fetch …
> Expand the REST API to return all snapshots for a specific document

- src/server/model.coffee
- src/server/rest.coffee
- src/server/useragent.coffee
I added a `/versions` endpoint which allows a client to request all versions of a document, in steps of a specified size.
The reason for adding this endpoint is that it will allow us to remove a whole lot of snapshots from the production database. They are currently taking up ~50GB, and it would be great if we can prune old snapshots.
However, the history slider requires a list of versions to scrub through. We used to get the versions straight from the snapshots, but now we can generate them dynamically. ✨ 
- Update the `share` dependency in the `package.json` file for the `tc-share` app to: `"share": "git://github.com/conversation/ShareJS.git#c6e804d"`.
For development I used `npm ln`, but YMMV.
- Fire up the server with `npm start`
-  Curl the new endpoint with a document ID: `curl …
> Add versions endpoint

- src/server/db/pg.coffee
`keep_snapshots` was an option we introduced to our fork, and we've now decided to stop using it - the data storage requirements are significant and we don't need them any more.
We plan to return to the standard sharejs behaviour of only keeping a single snapshot per document to optimise the common case of needing the latest version of a document.
I'm not sure how this discrepancy was introduced, but we haven't noticed before now because we've had keep_snapshots enabled for as long as we've used sharejs. I tested setting `keep_snapshots: false` locally in preparation for the upcoming changes and found the issue.
Once this has been deployed, we may want to consider reverting the original change in our fork to remove the `keep_snapshots` option all together. There's no use maintaining it in …
> SQL in both of the keep_snapshot code paths must use same number of variables

- src/server/db/pg.coffee
- src/server/model.coffee
- src/server/rest.coffee
- src/server/useragent.coffee
This additional REST endpoint was added to our sharejs fork (in #5) as a way to fetch data for the history slider on drafts#edit.
We've since added a `/versions` REST endpoint and have switched to that for the same purpose. In the interests of reducing the delta between our fork and upstream, let's remove the unused endpoint.
> ShareJS Cleanup 1/2: Revert "Merge pull request #5 from conversation/get-snapshots"

- package.json
@RohanM and I discovered that if you lock `coffee-script` (to get consistent code generation) and `shelljs`  (so it actually compiles in the first place). We can actually start developing on this fork.
> Lock dependencies

- README.md
- bin/exampleserver
- bin/options.js
- src/server/index.coffee
The docs were previously a bit misleading, because they encouraged you to listen with express/connect, when this method does not work with websockets. You must listen with the `http.Server` returned by the `sharejs.attach` method for websockets to work.
> Improve documentation to make it easier to support websockets

- src/server/db/pg.coffee
This is assuming that the schema doesn't already exist, which in our use case is not true, because we just use the public schema.
In the case where you do configure sharejs to use the public schema this would previously error as it tried to create it again.
We just want to create the schema if it doesn't already exist.
> Fix auto table creation

- src/server/db/pg.coffee
- src/server/model.coffee
- src/server/rest.coffee
- src/server/useragent.coffee
- test/model.coffee
This is is no way ready to be merged or reviewed! I'm just hacking around :eyes: 
The existing REST API allows the latest version of a document to be requested using:
```
GET /doc/123abc
```
This expands the API to allow a specific version to be requested:
```
GET /doc/123abc?v=10
```
It works, however the current implementation is inefficient. It relies on the DB containing every operation from 0 to the requested version, then applying them in order. This has a few implications:
1. Sequential requests for versions 10 and 11 will fetch all operations from 1-10, apply them and return version 10, then fetch all operations from 1-11, apply them and return version 11. Imagine requesting version 3000 and 3001.
2. If any operations are missing (like for all our drafts) then the request will …
> Expand the REST API to allow a specific document version to be returned

- src/server/websocket.coffee
If we don't emit `'close'` to the wrapper, it will never be handled in the [`sessionHandler`](https://github.com/conversation/ShareJS/blob/master/src/server/session.coffee#L351), so the event listeners on `agent` keep a reference to the event emitter wrapper indefinitely.
This should fix the memory leak we're currently seeing with websocket clients.
> TC-382 Fix memory leak from not handling defunct websocket clients correctly

- bin/exampleserver
- src/server/websocket.coffee
Adds a really basic stats tracking callback to websocket server, so we can keep an eye on active websocket connections in datadog.
> TC-394 Track websocket stats

- src/client/textarea.coffee
- webclient/textarea.js
I suspect the "textInput" was a typo/mistake in the original code, as this is a jQuery event, but here we are operating on native elements.
"input" is what fires when correcting a spelling mistake, and it has good compatibility across all decent browsers since IE9, so I'm fairly confident this is a safe change. https://caniuse.com/#feat=input-event
To test it out:
1) `npm install && ./bin/example-server`
2) Load up two browser windows pointing at http://localhost:8000/
3) Intentionally make a typo, eg "footbakk" (observing that the changes propagate to both clients up until this point)
4) In one window, right click the typo and correct it to "football"
5) On master this change will not propagate correctly, on this branch it will
> Listen to input in addition to other events in textarea client

- .dependabot/config.yml
Same as https://github.com/conversation/tc/pull/9793:
We'd like to make sure we're staying on top of any important security
fixes in our dependencies. Github acquired dependabot last year and made
it free to use, which is useful since that can help us do exactly that.
This adds a dependabot config file that should result in automated PRs
providing security fixes for JS dependencies.
> Configure dependabot for security updates

- .github/workflows/test.yml
- .travis.yml
Travis CI was still giving me that unknown error when I tried to set this repo up on the .com product, so might as well just use github actions considering it wasn't too difficult to set up.
> Switch from Travis CI to GitHub Actions

- README.md
We're no longer using Travis since https://github.com/conversation/ShareJS/pull/39.
Let's replace its badge as well.
> Replace Travis badge with GitHub actions

- src/server/model.coffee
- src/types/json.coffee
We're still getting intermittent "Deleted string does not match" errors despite some of the other fixes applied, hoping that just logging the strings attempted to be deleted will reveal the problem.
To test (assuming starting from a blank slate):
```
npm install && npm run build
createdb sharejs_example
bin/sharejs
```
Now we need to create a json type document with a text type subdocument, insert a string, then give it a bad delete op:
Create a document
`curl -X PUT -H 'Content-Type: application/json' -d '{"type": "json"}' http://localhost:9000/doc/test`
Post an object insert op to insert an empty object to create a json document type
`curl -X POST -H 'Content-Type: application/json' -d '[{ "p": [], "oi": {} }]' http://localhost:9000/doc/test?v=0`
Object insert on the key "test", …
> Improve error logged when there's an exception applying ops

- package.json
No longer required after removing browserchannel, missed this yesterday in https://github.com/conversation/ShareJS/pull/51
> Remove connect as a dependency

- package.json
This doesn't get us anywhere near on the latest version, but this at least resolves some security issues with the ancient 0.4.32 version. 
Going to 3.x and beyond will need some code changes by the looks of it.
> Upgrade ws to 2.3.1

- Cakefile
- package.json
To test, run the various npm scripts which use different parts of the cakefile:
```
npm run build
npm run test
npm run prepublish
```
None should give any errors or any build output changes.
> Upgrade shelljs

- src/server/websocket.coffee
We picked up this issue because the stats were returning nothing, so out of caution we rolled back to and older version in production until I could look at this again.
Turns out the type of `wss.clients` [changed](https://github.com/websockets/ws/issues/934) from `Array` to `Set`, so while all the document editing and so on was working fine, our stats tracking and inactive client reaping was not. This fixes both of those issues so we should be good to proceed with the upgrade again.
(note that I added some temporary logging to make it more obvious when an inactive connection was reaped)
To test, run the `bin/exampleserver` and visit http://localhost:8000/
You should see the stats tracking in the example server working correctly (it currently does not on master).
> Fix stats track and inactive client reaping

- bin/exampleserver
- bin/sharejs
- package.json
- src/client/doc.coffee
- src/client/index.coffee
- src/server/useragent.coffee
- test/helpers/webclient.coffee
- test/integration.coffee
- test/server.coffee
- test/sockjs.coffee
- tests.coffee
We had actually stopped using it a while back, so this doesn't change much other than removing the packages and cleaning up some irrelevant comments.
Can boot up `./bin/exampleserver` to sanity check if you'd like.
> Remove remnants of socket.io

- package.json
We technically don't use this, but it has some value in supporting tests that have not been ported to websocket yet.
Nothing to test manually, covered by automated tests.
> Upgrade sockjs to 0.3.24
